name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential pkg-config libdrm-dev

    - name: Configure with CMake
      run: cmake .

    - name: Build with Make
      run: make

    - name: Make binary executable
      run: chmod +x oberon-governor

    - name: Upload binary to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: oberon-governor ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: |
          **oberon-governor** is a CMake-based CPU frequency scaling governor.

          This release includes the compiled `oberon-governor` binary for Linux systems.

        files: oberon-governor
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

