name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers when pushing tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential zip

    - name: Configure with CMake
      run: cmake .

    - name: Build with Make
      run: make

    - name: Package binary as ZIP
      run: |
        mkdir release
        cp oberon-governor release/
        cd release
        zip oberon-governor.zip oberon-governor
        mv oberon-governor.zip ../

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: oberon-governor ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: |
          **oberon-governor** is a CMake-based CPU frequency scaling governor.

          ### Highlights
          - Automatic release from CI
          - Built using GitHub Actions
          - Includes precompiled binary for Linux

        files: oberon-governor.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
